export interface Country {
  plName: string;
  enName: string;
  alfa2: string;
  alfa3: string;
  numeric: number;
}

export class Countries {
  static allCountries: Array<Country> = [
    {
      plName: 'Afganistan',
      enName: 'Afghanistan',
      alfa2: 'AF',
      alfa3: 'AFG',
      numeric: 4,
    },
    {
      plName: 'Albania',
      enName: 'Albania',
      alfa2: 'AL',
      alfa3: 'ALB',
      numeric: 8,
    },
    {
      plName: 'Algieria',
      enName: 'Algeria',
      alfa2: 'DZ',
      alfa3: 'DZA',
      numeric: 12,
    },
    {
      plName: 'Andora',
      enName: 'Andorra',
      alfa2: 'AD',
      alfa3: 'AND',
      numeric: 20,
    },
    {
      plName: 'Angola',
      enName: 'Angola',
      alfa2: 'AO',
      alfa3: 'AGO',
      numeric: 24,
    },
    {
      plName: 'Anguilla',
      enName: 'Anguilla',
      alfa2: 'AI',
      alfa3: 'AIA',
      numeric: 660,
    },
    {
      plName: 'Antarktyka',
      enName: 'Antarctica',
      alfa2: 'AQ',
      alfa3: 'ATA',
      numeric: 10,
    },
    {
      plName: 'Antigua i Barbuda',
      enName: 'Antigua and Barbuda',
      alfa2: 'AG',
      alfa3: 'ATG',
      numeric: 28,
    },
    {
      plName: 'Arabia Saudyjska',
      enName: 'Saudi Arabia',
      alfa2: 'SA',
      alfa3: 'SAU',
      numeric: 682,
    },
    {
      plName: 'Argentyna',
      enName: 'Argentina',
      alfa2: 'AR',
      alfa3: 'ARG',
      numeric: 32,
    },
    {
      plName: 'Armenia',
      enName: 'Armenia',
      alfa2: 'AM',
      alfa3: 'ARM',
      numeric: 51,
    },
    {
      plName: 'Aruba',
      enName: 'Aruba',
      alfa2: 'AW',
      alfa3: 'ABW',
      numeric: 533,
    },
    {
      plName: 'Australia',
      enName: 'Australia',
      alfa2: 'AU',
      alfa3: 'AUS',
      numeric: 36,
    },
    {
      plName: 'Austria',
      enName: 'Austria',
      alfa2: 'AT',
      alfa3: 'AUT',
      numeric: 40,
    },
    {
      plName: 'Azerbejdżan',
      enName: 'Azerbaijan',
      alfa2: 'AZ',
      alfa3: 'AZE',
      numeric: 31,
    },
    {
      plName: 'Bahamy',
      enName: 'Bahamas',
      alfa2: 'BS',
      alfa3: 'BHS',
      numeric: 44,
    },
    {
      plName: 'Bahrajn',
      enName: 'Bahrain',
      alfa2: 'BH',
      alfa3: 'BHR',
      numeric: 48,
    },
    {
      plName: 'Bangladesz',
      enName: 'Bangladesh',
      alfa2: 'BD',
      alfa3: 'BGD',
      numeric: 50,
    },
    {
      plName: 'Barbados',
      enName: 'Barbados',
      alfa2: 'BB',
      alfa3: 'BRB',
      numeric: 52,
    },
    {
      plName: 'Belgia',
      enName: 'Belgium',
      alfa2: 'BE',
      alfa3: 'BEL',
      numeric: 56,
    },
    {
      plName: 'Belize',
      enName: 'Belize',
      alfa2: 'BZ',
      alfa3: 'BLZ',
      numeric: 84,
    },
    {
      plName: 'Benin',
      enName: 'Benin',
      alfa2: 'BJ',
      alfa3: 'BEN',
      numeric: 204,
    },
    {
      plName: 'Bermudy',
      enName: 'Bermuda',
      alfa2: 'BM',
      alfa3: 'BMU',
      numeric: 60,
    },
    {
      plName: 'Bhutan',
      enName: 'Bhutan',
      alfa2: 'BT',
      alfa3: 'BTN',
      numeric: 64,
    },
    {
      plName: 'Białoruś',
      enName: 'Belarus',
      alfa2: 'BY',
      alfa3: 'BLR',
      numeric: 112,
    },
    {
      plName: 'Boliwia',
      enName: 'Bolivia, Plurinational State of',
      alfa2: 'BO',
      alfa3: 'BOL',
      numeric: 68,
    },
    {
      plName: 'Bonaire, Sint Eustatius i Saba',
      enName: 'Bonaire, Sint Eustatius and Saba',
      alfa2: 'BQ',
      alfa3: 'BES',
      numeric: 535,
    },
    {
      plName: 'Bośnia i Hercegowina',
      enName: 'Bosnia and Herzegovina',
      alfa2: 'BA',
      alfa3: 'BIH',
      numeric: 70,
    },
    {
      plName: 'Botswana',
      enName: 'Botswana',
      alfa2: 'BW',
      alfa3: 'BWA',
      numeric: 72,
    },
    {
      plName: 'Brazylia',
      enName: 'Brazil',
      alfa2: 'BR',
      alfa3: 'BRA',
      numeric: 76,
    },
    {
      plName: 'Brunei',
      enName: 'Brunei Darussalam',
      alfa2: 'BN',
      alfa3: 'BRN',
      numeric: 96,
    },
    {
      plName: 'Brytyjskie Terytorium Oceanu Indyjskiego',
      enName: 'British Indian Ocean Territory',
      alfa2: 'IO',
      alfa3: 'IOT',
      numeric: 86,
    },
    {
      plName: 'Brytyjskie Wyspy Dziewicze',
      enName: 'Virgin Islands, British',
      alfa2: 'VG',
      alfa3: 'VGB',
      numeric: 92,
    },
    {
      plName: 'Bułgaria',
      enName: 'Bulgaria',
      alfa2: 'BG',
      alfa3: 'BGR',
      numeric: 100,
    },
    {
      plName: 'Burkina Faso',
      enName: 'Burkina Faso',
      alfa2: 'BF',
      alfa3: 'BFA',
      numeric: 854,
    },
    {
      plName: 'Burundi',
      enName: 'Burundi',
      alfa2: 'BI',
      alfa3: 'BDI',
      numeric: 108,
    },
    {
      plName: 'Chile',
      enName: 'Chile',
      alfa2: 'CL',
      alfa3: 'CHL',
      numeric: 152,
    },
    {
      plName: 'Chiny',
      enName: 'China',
      alfa2: 'CN',
      alfa3: 'CHN',
      numeric: 156,
    },
    {
      plName: 'Chorwacja',
      enName: 'Croatia',
      alfa2: 'HR',
      alfa3: 'HRV',
      numeric: 191,
    },
    {
      plName: 'Curaçao',
      enName: 'Curaçao',
      alfa2: 'CW',
      alfa3: 'CUW',
      numeric: 531,
    },
    {
      plName: 'Cypr',
      enName: 'Cyprus',
      alfa2: 'CY',
      alfa3: 'CYP',
      numeric: 196,
    },
    { plName: 'Czad', enName: 'Chad', alfa2: 'TD', alfa3: 'TCD', numeric: 148 },
    {
      plName: 'Czarnogóra',
      enName: 'Montenegro',
      alfa2: 'ME',
      alfa3: 'MNE',
      numeric: 499,
    },
    {
      plName: 'Czechy',
      enName: 'Czechia',
      alfa2: 'CZ',
      alfa3: 'CZE',
      numeric: 203,
    },
    {
      plName: 'Dalekie Wyspy Mniejsze Stanów Zjednoczonych',
      enName: 'United States Minor Outlying Islands',
      alfa2: 'UM',
      alfa3: 'UMI',
      numeric: 581,
    },
    {
      plName: 'Dania',
      enName: 'Denmark',
      alfa2: 'DK',
      alfa3: 'DNK',
      numeric: 208,
    },
    {
      plName: 'Demokratyczna Republika Konga',
      enName: 'Congo, the Democratic Republic of the',
      alfa2: 'CD',
      alfa3: 'COD',
      numeric: 180,
    },
    {
      plName: 'Dominika',
      enName: 'Dominica',
      alfa2: 'DM',
      alfa3: 'DMA',
      numeric: 212,
    },
    {
      plName: 'Dominikana',
      enName: 'Dominican Republic',
      alfa2: 'DO',
      alfa3: 'DOM',
      numeric: 214,
    },
    {
      plName: 'Dżibuti',
      enName: 'Djibouti',
      alfa2: 'DJ',
      alfa3: 'DJI',
      numeric: 262,
    },
    {
      plName: 'Egipt',
      enName: 'Egypt',
      alfa2: 'EG',
      alfa3: 'EGY',
      numeric: 818,
    },
    {
      plName: 'Ekwador',
      enName: 'Ecuador',
      alfa2: 'EC',
      alfa3: 'ECU',
      numeric: 218,
    },
    {
      plName: 'Erytrea',
      enName: 'Eritrea',
      alfa2: 'ER',
      alfa3: 'ERI',
      numeric: 232,
    },
    {
      plName: 'Estonia',
      enName: 'Estonia',
      alfa2: 'EE',
      alfa3: 'EST',
      numeric: 233,
    },
    {
      plName: 'Eswatini',
      enName: 'Eswatini',
      alfa2: 'SZ',
      alfa3: 'SWZ',
      numeric: 748,
    },
    {
      plName: 'Etiopia',
      enName: 'Ethiopia',
      alfa2: 'ET',
      alfa3: 'ETH',
      numeric: 231,
    },
    {
      plName: 'Falklandy',
      enName: 'Falkland Islands (Malvinas)',
      alfa2: 'FK',
      alfa3: 'FLK',
      numeric: 238,
    },
    {
      plName: 'Fidżi',
      enName: 'Fiji',
      alfa2: 'FJ',
      alfa3: 'FJI',
      numeric: 242,
    },
    {
      plName: 'Filipiny',
      enName: 'Philippines',
      alfa2: 'PH',
      alfa3: 'PHL',
      numeric: 608,
    },
    {
      plName: 'Finlandia',
      enName: 'Finland',
      alfa2: 'FI',
      alfa3: 'FIN',
      numeric: 246,
    },
    {
      plName: 'Francja',
      enName: 'France',
      alfa2: 'FR',
      alfa3: 'FRA',
      numeric: 250,
    },
    {
      plName: 'Francuskie Terytoria Południowe i Antarktyczne',
      enName: 'French Southern Territories',
      alfa2: 'TF',
      alfa3: 'ATF',
      numeric: 260,
    },
    {
      plName: 'Gabon',
      enName: 'Gabon',
      alfa2: 'GA',
      alfa3: 'GAB',
      numeric: 266,
    },
    {
      plName: 'Gambia',
      enName: 'Gambia',
      alfa2: 'GM',
      alfa3: 'GMB',
      numeric: 270,
    },
    {
      plName: 'Georgia Południowa i Sandwich Południowy',
      enName: 'South Georgia and the South Sandwich Islands',
      alfa2: 'GS',
      alfa3: 'SGS',
      numeric: 239,
    },
    {
      plName: 'Ghana',
      enName: 'Ghana',
      alfa2: 'GH',
      alfa3: 'GHA',
      numeric: 288,
    },
    {
      plName: 'Gibraltar',
      enName: 'Gibraltar',
      alfa2: 'GI',
      alfa3: 'GIB',
      numeric: 292,
    },
    {
      plName: 'Grecja',
      enName: 'Greece',
      alfa2: 'GR',
      alfa3: 'GRC',
      numeric: 300,
    },
    {
      plName: 'Grenada',
      enName: 'Grenada',
      alfa2: 'GD',
      alfa3: 'GRD',
      numeric: 308,
    },
    {
      plName: 'Grenlandia',
      enName: 'Greenland',
      alfa2: 'GL',
      alfa3: 'GRL',
      numeric: 304,
    },
    {
      plName: 'Gruzja',
      enName: 'Georgia',
      alfa2: 'GE',
      alfa3: 'GEO',
      numeric: 268,
    },
    { plName: 'Guam', enName: 'Guam', alfa2: 'GU', alfa3: 'GUM', numeric: 316 },
    {
      plName: 'Guernsey',
      enName: 'Guernsey',
      alfa2: 'GG',
      alfa3: 'GGY',
      numeric: 831,
    },
    {
      plName: 'Gujana Francuska',
      enName: 'French Guiana',
      alfa2: 'GF',
      alfa3: 'GUF',
      numeric: 254,
    },
    {
      plName: 'Gujana',
      enName: 'Guyana',
      alfa2: 'GY',
      alfa3: 'GUY',
      numeric: 328,
    },
    {
      plName: 'Gwadelupa',
      enName: 'Guadeloupe',
      alfa2: 'GP',
      alfa3: 'GLP',
      numeric: 312,
    },
    {
      plName: 'Gwatemala',
      enName: 'Guatemala',
      alfa2: 'GT',
      alfa3: 'GTM',
      numeric: 320,
    },
    {
      plName: 'Gwinea Bissau',
      enName: 'Guinea-Bissau',
      alfa2: 'GW',
      alfa3: 'GNB',
      numeric: 624,
    },
    {
      plName: 'Gwinea Równikowa',
      enName: 'Equatorial Guinea',
      alfa2: 'GQ',
      alfa3: 'GNQ',
      numeric: 226,
    },
    {
      plName: 'Gwinea',
      enName: 'Guinea',
      alfa2: 'GN',
      alfa3: 'GIN',
      numeric: 324,
    },
    {
      plName: 'Haiti',
      enName: 'Haiti',
      alfa2: 'HT',
      alfa3: 'HTI',
      numeric: 332,
    },
    {
      plName: 'Hiszpania',
      enName: 'Spain',
      alfa2: 'ES',
      alfa3: 'ESP',
      numeric: 724,
    },
    {
      plName: 'Holandia',
      enName: 'Netherlands',
      alfa2: 'NL',
      alfa3: 'NLD',
      numeric: 528,
    },
    {
      plName: 'Honduras',
      enName: 'Honduras',
      alfa2: 'HN',
      alfa3: 'HND',
      numeric: 340,
    },
    {
      plName: 'Hongkong',
      enName: 'Hong Kong',
      alfa2: 'HK',
      alfa3: 'HKG',
      numeric: 344,
    },
    {
      plName: 'Indie',
      enName: 'India',
      alfa2: 'IN',
      alfa3: 'IND',
      numeric: 356,
    },
    {
      plName: 'Indonezja',
      enName: 'Indonesia',
      alfa2: 'ID',
      alfa3: 'IDN',
      numeric: 360,
    },
    { plName: 'Irak', enName: 'Iraq', alfa2: 'IQ', alfa3: 'IRQ', numeric: 368 },
    {
      plName: 'Iran',
      enName: 'Iran, Islamic Republic of',
      alfa2: 'IR',
      alfa3: 'IRN',
      numeric: 364,
    },
    {
      plName: 'Irlandia',
      enName: 'Ireland',
      alfa2: 'IE',
      alfa3: 'IRL',
      numeric: 372,
    },
    {
      plName: 'Islandia',
      enName: 'Iceland',
      alfa2: 'IS',
      alfa3: 'ISL',
      numeric: 352,
    },
    {
      plName: 'Izrael',
      enName: 'Israel',
      alfa2: 'IL',
      alfa3: 'ISR',
      numeric: 376,
    },
    {
      plName: 'Jamajka',
      enName: 'Jamaica',
      alfa2: 'JM',
      alfa3: 'JAM',
      numeric: 388,
    },
    {
      plName: 'Japonia',
      enName: 'Japan',
      alfa2: 'JP',
      alfa3: 'JPN',
      numeric: 392,
    },
    {
      plName: 'Jemen',
      enName: 'Yemen',
      alfa2: 'YE',
      alfa3: 'YEM',
      numeric: 887,
    },
    {
      plName: 'Jersey',
      enName: 'Jersey',
      alfa2: 'JE',
      alfa3: 'JEY',
      numeric: 832,
    },
    {
      plName: 'Jordania',
      enName: 'Jordan',
      alfa2: 'JO',
      alfa3: 'JOR',
      numeric: 400,
    },
    {
      plName: 'Kajmany',
      enName: 'Cayman Islands',
      alfa2: 'KY',
      alfa3: 'CYM',
      numeric: 136,
    },
    {
      plName: 'Kambodża',
      enName: 'Cambodia',
      alfa2: 'KH',
      alfa3: 'KHM',
      numeric: 116,
    },
    {
      plName: 'Kamerun',
      enName: 'Cameroon',
      alfa2: 'CM',
      alfa3: 'CMR',
      numeric: 120,
    },
    {
      plName: 'Kanada',
      enName: 'Canada',
      alfa2: 'CA',
      alfa3: 'CAN',
      numeric: 124,
    },
    {
      plName: 'Katar',
      enName: 'Qatar',
      alfa2: 'QA',
      alfa3: 'QAT',
      numeric: 634,
    },
    {
      plName: 'Kazachstan',
      enName: 'Kazakhstan',
      alfa2: 'KZ',
      alfa3: 'KAZ',
      numeric: 398,
    },
    {
      plName: 'Kenia',
      enName: 'Kenya',
      alfa2: 'KE',
      alfa3: 'KEN',
      numeric: 404,
    },
    {
      plName: 'Kirgistan',
      enName: 'Kyrgyzstan',
      alfa2: 'KG',
      alfa3: 'KGZ',
      numeric: 417,
    },
    {
      plName: 'Kiribati',
      enName: 'Kiribati',
      alfa2: 'KI',
      alfa3: 'KIR',
      numeric: 296,
    },
    {
      plName: 'Kolumbia',
      enName: 'Colombia',
      alfa2: 'CO',
      alfa3: 'COL',
      numeric: 170,
    },
    {
      plName: 'Komory',
      enName: 'Comoros',
      alfa2: 'KM',
      alfa3: 'COM',
      numeric: 174,
    },
    {
      plName: 'Kongo',
      enName: 'Congo',
      alfa2: 'CG',
      alfa3: 'COG',
      numeric: 178,
    },
    {
      plName: 'Korea Południowa',
      enName: 'Korea, Republic of',
      alfa2: 'KR',
      alfa3: 'KOR',
      numeric: 410,
    },
    {
      plName: 'Korea Północna',
      enName: 'Korea, Democratic People’s Republic of',
      alfa2: 'KP',
      alfa3: 'PRK',
      numeric: 408,
    },
    {
      plName: 'Kostaryka',
      enName: 'Costa Rica',
      alfa2: 'CR',
      alfa3: 'CRI',
      numeric: 188,
    },
    { plName: 'Kuba', enName: 'Cuba', alfa2: 'CU', alfa3: 'CUB', numeric: 192 },
    {
      plName: 'Kuwejt',
      enName: 'Kuwait',
      alfa2: 'KW',
      alfa3: 'KWT',
      numeric: 414,
    },
    {
      plName: 'Laos',
      enName: 'Lao People’s Democratic Republic',
      alfa2: 'LA',
      alfa3: 'LAO',
      numeric: 418,
    },
    {
      plName: 'Lesotho',
      enName: 'Lesotho',
      alfa2: 'LS',
      alfa3: 'LSO',
      numeric: 426,
    },
    {
      plName: 'Liban',
      enName: 'Lebanon',
      alfa2: 'LB',
      alfa3: 'LBN',
      numeric: 422,
    },
    {
      plName: 'Liberia',
      enName: 'Liberia',
      alfa2: 'LR',
      alfa3: 'LBR',
      numeric: 430,
    },
    {
      plName: 'Libia',
      enName: 'Libyan Arab Jamahiriya',
      alfa2: 'LY',
      alfa3: 'LBY',
      numeric: 434,
    },
    {
      plName: 'Liechtenstein',
      enName: 'Liechtenstein',
      alfa2: 'LI',
      alfa3: 'LIE',
      numeric: 438,
    },
    {
      plName: 'Litwa',
      enName: 'Lithuania',
      alfa2: 'LT',
      alfa3: 'LTU',
      numeric: 440,
    },
    {
      plName: 'Luksemburg',
      enName: 'Luxembourg',
      alfa2: 'LU',
      alfa3: 'LUX',
      numeric: 442,
    },
    {
      plName: 'Łotwa',
      enName: 'Latvia',
      alfa2: 'LV',
      alfa3: 'LVA',
      numeric: 428,
    },
    {
      plName: 'Macedonia Północna',
      enName:
        'Macedonia, the former Yugoslav Republic of[potrzebna aktualizacja?]',
      alfa2: 'MK',
      alfa3: 'MKD',
      numeric: 807,
    },
    {
      plName: 'Madagaskar',
      enName: 'Madagascar',
      alfa2: 'MG',
      alfa3: 'MDG',
      numeric: 450,
    },
    {
      plName: 'Majotta',
      enName: 'Mayotte',
      alfa2: 'YT',
      alfa3: 'MYT',
      numeric: 175,
    },
    {
      plName: 'Makau',
      enName: 'Macao',
      alfa2: 'MO',
      alfa3: 'MAC',
      numeric: 446,
    },
    {
      plName: 'Malawi',
      enName: 'Malawi',
      alfa2: 'MW',
      alfa3: 'MWI',
      numeric: 454,
    },
    {
      plName: 'Malediwy',
      enName: 'Maldives',
      alfa2: 'MV',
      alfa3: 'MDV',
      numeric: 462,
    },
    {
      plName: 'Malezja',
      enName: 'Malaysia',
      alfa2: 'MY',
      alfa3: 'MYS',
      numeric: 458,
    },
    { plName: 'Mali', enName: 'Mali', alfa2: 'ML', alfa3: 'MLI', numeric: 466 },
    {
      plName: 'Malta',
      enName: 'Malta',
      alfa2: 'MT',
      alfa3: 'MLT',
      numeric: 470,
    },
    {
      plName: 'Mariany Północne',
      enName: 'Northern Mariana Islands',
      alfa2: 'MP',
      alfa3: 'MNP',
      numeric: 580,
    },
    {
      plName: 'Maroko',
      enName: 'Morocco',
      alfa2: 'MA',
      alfa3: 'MAR',
      numeric: 504,
    },
    {
      plName: 'Martynika',
      enName: 'Martinique',
      alfa2: 'MQ',
      alfa3: 'MTQ',
      numeric: 474,
    },
    {
      plName: 'Mauretania',
      enName: 'Mauritania',
      alfa2: 'MR',
      alfa3: 'MRT',
      numeric: 478,
    },
    {
      plName: 'Mauritius',
      enName: 'Mauritius',
      alfa2: 'MU',
      alfa3: 'MUS',
      numeric: 480,
    },
    {
      plName: 'Meksyk',
      enName: 'Mexico',
      alfa2: 'MX',
      alfa3: 'MEX',
      numeric: 484,
    },
    {
      plName: 'Mikronezja',
      enName: 'Micronesia, Federated States of',
      alfa2: 'FM',
      alfa3: 'FSM',
      numeric: 583,
    },
    {
      plName: 'Mjanma',
      enName: 'Myanmar',
      alfa2: 'MM',
      alfa3: 'MMR',
      numeric: 104,
    },
    {
      plName: 'Mołdawia',
      enName: 'Moldova, Republic of',
      alfa2: 'MD',
      alfa3: 'MDA',
      numeric: 498,
    },
    {
      plName: 'Monako',
      enName: 'Monaco',
      alfa2: 'MC',
      alfa3: 'MCO',
      numeric: 492,
    },
    {
      plName: 'Mongolia',
      enName: 'Mongolia',
      alfa2: 'MN',
      alfa3: 'MNG',
      numeric: 496,
    },
    {
      plName: 'Montserrat',
      enName: 'Montserrat',
      alfa2: 'MS',
      alfa3: 'MSR',
      numeric: 500,
    },
    {
      plName: 'Mozambik',
      enName: 'Mozambique',
      alfa2: 'MZ',
      alfa3: 'MOZ',
      numeric: 508,
    },
    {
      plName: 'Namibia',
      enName: 'Namibia',
      alfa2: 'NA',
      alfa3: 'NAM',
      numeric: 516,
    },
    {
      plName: 'Nauru',
      enName: 'Nauru',
      alfa2: 'NR',
      alfa3: 'NRU',
      numeric: 520,
    },
    {
      plName: 'Nepal',
      enName: 'Nepal',
      alfa2: 'NP',
      alfa3: 'NPL',
      numeric: 524,
    },
    {
      plName: 'Niemcy',
      enName: 'Germany',
      alfa2: 'DE',
      alfa3: 'DEU',
      numeric: 276,
    },
    {
      plName: 'Niger',
      enName: 'Niger',
      alfa2: 'NE',
      alfa3: 'NER',
      numeric: 562,
    },
    {
      plName: 'Nigeria',
      enName: 'Nigeria',
      alfa2: 'NG',
      alfa3: 'NGA',
      numeric: 566,
    },
    {
      plName: 'Nikaragua',
      enName: 'Nicaragua',
      alfa2: 'NI',
      alfa3: 'NIC',
      numeric: 558,
    },
    { plName: 'Niue', enName: 'Niue', alfa2: 'NU', alfa3: 'NIU', numeric: 570 },
    {
      plName: 'Norfolk',
      enName: 'Norfolk Island',
      alfa2: 'NF',
      alfa3: 'NFK',
      numeric: 574,
    },
    {
      plName: 'Norwegia',
      enName: 'Norway',
      alfa2: 'NO',
      alfa3: 'NOR',
      numeric: 578,
    },
    {
      plName: 'Nowa Kaledonia',
      enName: 'New Caledonia',
      alfa2: 'NC',
      alfa3: 'NCL',
      numeric: 540,
    },
    {
      plName: 'Nowa Zelandia',
      enName: 'New Zealand',
      alfa2: 'NZ',
      alfa3: 'NZL',
      numeric: 554,
    },
    { plName: 'Oman', enName: 'Oman', alfa2: 'OM', alfa3: 'OMN', numeric: 512 },
    {
      plName: 'Pakistan',
      enName: 'Pakistan',
      alfa2: 'PK',
      alfa3: 'PAK',
      numeric: 586,
    },
    {
      plName: 'Palau',
      enName: 'Palau',
      alfa2: 'PW',
      alfa3: 'PLW',
      numeric: 585,
    },
    {
      plName: 'Palestyna',
      enName: 'Palestinian Territory, Occupied',
      alfa2: 'PS',
      alfa3: 'PSE',
      numeric: 275,
    },
    {
      plName: 'Panama',
      enName: 'Panama',
      alfa2: 'PA',
      alfa3: 'PAN',
      numeric: 591,
    },
    {
      plName: 'Papua-Nowa Gwinea',
      enName: 'Papua New Guinea',
      alfa2: 'PG',
      alfa3: 'PNG',
      numeric: 598,
    },
    {
      plName: 'Paragwaj',
      enName: 'Paraguay',
      alfa2: 'PY',
      alfa3: 'PRY',
      numeric: 600,
    },
    { plName: 'Peru', enName: 'Peru', alfa2: 'PE', alfa3: 'PER', numeric: 604 },
    {
      plName: 'Pitcairn',
      enName: 'Pitcairn',
      alfa2: 'PN',
      alfa3: 'PCN',
      numeric: 612,
    },
    {
      plName: 'Polinezja Francuska',
      enName: 'French Polynesia',
      alfa2: 'PF',
      alfa3: 'PYF',
      numeric: 258,
    },
    {
      plName: 'Polska',
      enName: 'Poland',
      alfa2: 'PL',
      alfa3: 'POL',
      numeric: 616,
    },
    {
      plName: 'Portoryko',
      enName: 'Puerto Rico',
      alfa2: 'PR',
      alfa3: 'PRI',
      numeric: 630,
    },
    {
      plName: 'Portugalia',
      enName: 'Portugal',
      alfa2: 'PT',
      alfa3: 'PRT',
      numeric: 620,
    },
    {
      plName: 'Południowa Afryka',
      enName: 'South Africa',
      alfa2: 'ZA',
      alfa3: 'ZAF',
      numeric: 710,
    },
    {
      plName: 'Republika Środkowoafrykańska',
      enName: 'Central African Republic',
      alfa2: 'CF',
      alfa3: 'CAF',
      numeric: 140,
    },
    {
      plName: 'Republika Zielonego Przylądka',
      enName: 'Cape Verde',
      alfa2: 'CV',
      alfa3: 'CPV',
      numeric: 132,
    },
    {
      plName: 'Reunion',
      enName: 'Réunion',
      alfa2: 'RE',
      alfa3: 'REU',
      numeric: 638,
    },
    {
      plName: 'Rosja',
      enName: 'Russian Federation',
      alfa2: 'RU',
      alfa3: 'RUS',
      numeric: 643,
    },
    {
      plName: 'Rumunia',
      enName: 'Romania',
      alfa2: 'RO',
      alfa3: 'ROU',
      numeric: 642,
    },
    {
      plName: 'Rwanda',
      enName: 'Rwanda',
      alfa2: 'RW',
      alfa3: 'RWA',
      numeric: 646,
    },
    {
      plName: 'Sahara Zachodnia',
      enName: 'Western Sahara',
      alfa2: 'EH',
      alfa3: 'ESH',
      numeric: 732,
    },
    {
      plName: 'Saint Kitts i Nevis',
      enName: 'Saint Kitts and Nevis',
      alfa2: 'KN',
      alfa3: 'KNA',
      numeric: 659,
    },
    {
      plName: 'Saint Lucia',
      enName: 'Saint Lucia',
      alfa2: 'LC',
      alfa3: 'LCA',
      numeric: 662,
    },
    {
      plName: 'Saint Vincent i Grenadyny',
      enName: 'Saint Vincent and the Grenadines',
      alfa2: 'VC',
      alfa3: 'VCT',
      numeric: 670,
    },
    {
      plName: 'Saint-Barthélemy',
      enName: 'Saint Barthélemy',
      alfa2: 'BL',
      alfa3: 'BLM',
      numeric: 652,
    },
    {
      plName: 'Saint-Martin',
      enName: 'Saint Martin (French part)',
      alfa2: 'MF',
      alfa3: 'MAF',
      numeric: 663,
    },
    {
      plName: 'Saint-Pierre i Miquelon',
      enName: 'Saint Pierre and Miquelon',
      alfa2: 'PM',
      alfa3: 'SPM',
      numeric: 666,
    },
    {
      plName: 'Salwador',
      enName: 'El Salvador',
      alfa2: 'SV',
      alfa3: 'SLV',
      numeric: 222,
    },
    {
      plName: 'Samoa Amerykańskie',
      enName: 'American Samoa',
      alfa2: 'AS',
      alfa3: 'ASM',
      numeric: 16,
    },
    {
      plName: 'Samoa',
      enName: 'Samoa',
      alfa2: 'WS',
      alfa3: 'WSM',
      numeric: 882,
    },
    {
      plName: 'San Marino',
      enName: 'San Marino',
      alfa2: 'SM',
      alfa3: 'SMR',
      numeric: 674,
    },
    {
      plName: 'Senegal',
      enName: 'Senegal',
      alfa2: 'SN',
      alfa3: 'SEN',
      numeric: 686,
    },
    {
      plName: 'Serbia',
      enName: 'Serbia',
      alfa2: 'RS',
      alfa3: 'SRB',
      numeric: 688,
    },
    {
      plName: 'Seszele',
      enName: 'Seychelles',
      alfa2: 'SC',
      alfa3: 'SYC',
      numeric: 690,
    },
    {
      plName: 'Sierra Leone',
      enName: 'Sierra Leone',
      alfa2: 'SL',
      alfa3: 'SLE',
      numeric: 694,
    },
    {
      plName: 'Singapur',
      enName: 'Singapore',
      alfa2: 'SG',
      alfa3: 'SGP',
      numeric: 702,
    },
    {
      plName: 'Sint Maarten',
      enName: 'Sint Maarten (Dutch part)',
      alfa2: 'SX',
      alfa3: 'SXM',
      numeric: 534,
    },
    {
      plName: 'Słowacja',
      enName: 'Slovakia',
      alfa2: 'SK',
      alfa3: 'SVK',
      numeric: 703,
    },
    {
      plName: 'Słowenia',
      enName: 'Slovenia',
      alfa2: 'SI',
      alfa3: 'SVN',
      numeric: 705,
    },
    {
      plName: 'Somalia',
      enName: 'Somalia',
      alfa2: 'SO',
      alfa3: 'SOM',
      numeric: 706,
    },
    {
      plName: 'Sri Lanka',
      enName: 'Sri Lanka',
      alfa2: 'LK',
      alfa3: 'LKA',
      numeric: 144,
    },
    {
      plName: 'Stany Zjednoczone',
      enName: 'United States',
      alfa2: 'US',
      alfa3: 'USA',
      numeric: 840,
    },
    {
      plName: 'Sudan',
      enName: 'Sudan',
      alfa2: 'SD',
      alfa3: 'SDN',
      numeric: 729,
    },
    {
      plName: 'Sudan Południowy',
      enName: 'South Sudan',
      alfa2: 'SS',
      alfa3: 'SSD',
      numeric: 728,
    },
    {
      plName: 'Surinam',
      enName: 'Suriname',
      alfa2: 'SR',
      alfa3: 'SUR',
      numeric: 740,
    },
    {
      plName: 'Svalbard i Jan Mayen',
      enName: 'Svalbard and Jan Mayen',
      alfa2: 'SJ',
      alfa3: 'SJM',
      numeric: 744,
    },
    {
      plName: 'Syria',
      enName: 'Syrian Arab Republic',
      alfa2: 'SY',
      alfa3: 'SYR',
      numeric: 760,
    },
    {
      plName: 'Szwajcaria',
      enName: 'Switzerland',
      alfa2: 'CH',
      alfa3: 'CHE',
      numeric: 756,
    },
    {
      plName: 'Szwecja',
      enName: 'Sweden',
      alfa2: 'SE',
      alfa3: 'SWE',
      numeric: 752,
    },
    {
      plName: 'Tadżykistan',
      enName: 'Tajikistan',
      alfa2: 'TJ',
      alfa3: 'TJK',
      numeric: 762,
    },
    {
      plName: 'Tajlandia',
      enName: 'Thailand',
      alfa2: 'TH',
      alfa3: 'THA',
      numeric: 764,
    },
    {
      plName: 'Tajwan',
      enName: 'Taiwan, Province of China',
      alfa2: 'TW',
      alfa3: 'TWN',
      numeric: 158,
    },
    {
      plName: 'Tanzania',
      enName: 'Tanzania, United Republic of',
      alfa2: 'TZ',
      alfa3: 'TZA',
      numeric: 834,
    },
    {
      plName: 'Timor Wschodni',
      enName: 'Timor-Leste',
      alfa2: 'TL',
      alfa3: 'TLS',
      numeric: 626,
    },
    { plName: 'Togo', enName: 'Togo', alfa2: 'TG', alfa3: 'TGO', numeric: 768 },
    {
      plName: 'Tokelau',
      enName: 'Tokelau',
      alfa2: 'TK',
      alfa3: 'TKL',
      numeric: 772,
    },
    {
      plName: 'Tonga',
      enName: 'Tonga',
      alfa2: 'TO',
      alfa3: 'TON',
      numeric: 776,
    },
    {
      plName: 'Trynidad i Tobago',
      enName: 'Trinidad and Tobago',
      alfa2: 'TT',
      alfa3: 'TTO',
      numeric: 780,
    },
    {
      plName: 'Tunezja',
      enName: 'Tunisia',
      alfa2: 'TN',
      alfa3: 'TUN',
      numeric: 788,
    },
    {
      plName: 'Turcja',
      enName: 'Turkey',
      alfa2: 'TR',
      alfa3: 'TUR',
      numeric: 792,
    },
    {
      plName: 'Turkmenistan',
      enName: 'Turkmenistan',
      alfa2: 'TM',
      alfa3: 'TKM',
      numeric: 795,
    },
    {
      plName: 'Turks i Caicos',
      enName: 'Turks and Caicos Islands',
      alfa2: 'TC',
      alfa3: 'TCA',
      numeric: 796,
    },
    {
      plName: 'Tuvalu',
      enName: 'Tuvalu',
      alfa2: 'TV',
      alfa3: 'TUV',
      numeric: 798,
    },
    {
      plName: 'Uganda',
      enName: 'Uganda',
      alfa2: 'UG',
      alfa3: 'UGA',
      numeric: 800,
    },
    {
      plName: 'Ukraina',
      enName: 'Ukraine',
      alfa2: 'UA',
      alfa3: 'UKR',
      numeric: 804,
    },
    {
      plName: 'Urugwaj',
      enName: 'Uruguay',
      alfa2: 'UY',
      alfa3: 'URY',
      numeric: 858,
    },
    {
      plName: 'Uzbekistan',
      enName: 'Uzbekistan',
      alfa2: 'UZ',
      alfa3: 'UZB',
      numeric: 860,
    },
    {
      plName: 'Vanuatu',
      enName: 'Vanuatu',
      alfa2: 'VU',
      alfa3: 'VUT',
      numeric: 548,
    },
    {
      plName: 'Wallis i Futuna',
      enName: 'Wallis and Futuna',
      alfa2: 'WF',
      alfa3: 'WLF',
      numeric: 876,
    },
    {
      plName: 'Watykan',
      enName: 'Holy See (Vatican City State)',
      alfa2: 'VA',
      alfa3: 'VAT',
      numeric: 336,
    },
    {
      plName: 'Wenezuela',
      enName: 'Venezuela, Bolivarian Republic of',
      alfa2: 'VE',
      alfa3: 'VEN',
      numeric: 862,
    },
    {
      plName: 'Węgry',
      enName: 'Hungary',
      alfa2: 'HU',
      alfa3: 'HUN',
      numeric: 348,
    },
    {
      plName: 'Wielka Brytania',
      enName: 'United Kingdom',
      alfa2: 'GB',
      alfa3: 'GBR',
      numeric: 826,
    },
    {
      plName: 'Wietnam',
      enName: 'Viet Nam',
      alfa2: 'VN',
      alfa3: 'VNM',
      numeric: 704,
    },
    {
      plName: 'Włochy',
      enName: 'Italy',
      alfa2: 'IT',
      alfa3: 'ITA',
      numeric: 380,
    },
    {
      plName: 'Wybrzeże Kości Słoniowej',
      enName: 'Côte d’Ivoire',
      alfa2: 'CI',
      alfa3: 'CIV',
      numeric: 384,
    },
    {
      plName: 'Wyspa Bouveta',
      enName: 'Bouvet Island',
      alfa2: 'BV',
      alfa3: 'BVT',
      numeric: 74,
    },
    {
      plName: 'Wyspa Bożego Narodzenia',
      enName: 'Christmas Island',
      alfa2: 'CX',
      alfa3: 'CXR',
      numeric: 162,
    },
    {
      plName: 'Wyspa Man',
      enName: 'Isle of Man',
      alfa2: 'IM',
      alfa3: 'IMN',
      numeric: 833,
    },
    {
      plName: 'Wyspa Świętej Heleny, Wyspa Wniebowstąpienia i Tristan da Cunha',
      enName: 'Saint Helena, Ascension and Tristan da Cunha',
      alfa2: 'SH',
      alfa3: 'SHN',
      numeric: 654,
    },
    {
      plName: 'Wyspy Alandzkie',
      enName: 'Åland Islands',
      alfa2: 'AX',
      alfa3: 'ALA',
      numeric: 248,
    },
    {
      plName: 'Wyspy Cooka',
      enName: 'Cook Islands',
      alfa2: 'CK',
      alfa3: 'COK',
      numeric: 184,
    },
    {
      plName: 'Wyspy Dziewicze Stanów Zjednoczonych',
      enName: 'Virgin Islands, U.S.',
      alfa2: 'VI',
      alfa3: 'VIR',
      numeric: 850,
    },
    {
      plName: 'Wyspy Heard i McDonalda',
      enName: 'Heard Island and McDonald Islands',
      alfa2: 'HM',
      alfa3: 'HMD',
      numeric: 334,
    },
    {
      plName: 'Wyspy Kokosowe',
      enName: 'Cocos (Keeling) Islands',
      alfa2: 'CC',
      alfa3: 'CCK',
      numeric: 166,
    },
    {
      plName: 'Wyspy Marshalla',
      enName: 'Marshall Islands',
      alfa2: 'MH',
      alfa3: 'MHL',
      numeric: 584,
    },
    {
      plName: 'Wyspy Owcze',
      enName: 'Faroe Islands',
      alfa2: 'FO',
      alfa3: 'FRO',
      numeric: 234,
    },
    {
      plName: 'Wyspy Salomona',
      enName: 'Solomon Islands',
      alfa2: 'SB',
      alfa3: 'SLB',
      numeric: 90,
    },
    {
      plName: 'Wyspy Świętego Tomasza i Książęca',
      enName: 'Sao Tome and Principe',
      alfa2: 'ST',
      alfa3: 'STP',
      numeric: 678,
    },
    {
      plName: 'Zambia',
      enName: 'Zambia',
      alfa2: 'ZM',
      alfa3: 'ZMB',
      numeric: 894,
    },
    {
      plName: 'Zimbabwe',
      enName: 'Zimbabwe',
      alfa2: 'ZW',
      alfa3: 'ZWE',
      numeric: 716,
    },
    {
      plName: 'Zjednoczone Emiraty Arabskie',
      enName: 'United Arab Emirates',
      alfa2: 'AE',
      alfa3: 'ARE',
      numeric: 784,
    },
  ];
  static selectedCountries: Array<Country> = [
    {
      plName: 'Argentyna',
      enName: 'Argentina',
      alfa2: 'AR',
      alfa3: 'ARG',
      numeric: 32,
    },
    {
      plName: 'Austria',
      enName: 'Austria',
      alfa2: 'AT',
      alfa3: 'AUT',
      numeric: 40,
    },
    {
      plName: 'Białoruś',
      enName: 'Belarus',
      alfa2: 'BY',
      alfa3: 'BLR',
      numeric: 112,
    },
    {
      plName: 'Chiny',
      enName: 'China',
      alfa2: 'CN',
      alfa3: 'CHN',
      numeric: 156,
    },
    {
      plName: 'Czechy',
      enName: 'Czechia',
      alfa2: 'CZ',
      alfa3: 'CZE',
      numeric: 203,
    },
    {
      plName: 'Finlandia',
      enName: 'Finland',
      alfa2: 'FI',
      alfa3: 'FIN',
      numeric: 246,
    },
    {
      plName: 'Francja',
      enName: 'France',
      alfa2: 'FR',
      alfa3: 'FRA',
      numeric: 250,
    },
    {
      plName: 'Hiszpania',
      enName: 'Spain',
      alfa2: 'ES',
      alfa3: 'ESP',
      numeric: 724,
    },
    {
      plName: 'Holandia',
      enName: 'Netherlands',
      alfa2: 'NL',
      alfa3: 'NLD',
      numeric: 528,
    },
    {
      plName: 'Hongkong',
      enName: 'Hong Kong',
      alfa2: 'HK',
      alfa3: 'HKG',
      numeric: 344,
    },
    {
      plName: 'Irlandia',
      enName: 'Ireland',
      alfa2: 'IE',
      alfa3: 'IRL',
      numeric: 372,
    },
    {
      plName: 'Izrael',
      enName: 'Israel',
      alfa2: 'IL',
      alfa3: 'ISR',
      numeric: 376,
    },
    {
      plName: 'Korea Południowa',
      enName: 'Korea, Republic of',
      alfa2: 'KR',
      alfa3: 'KOR',
      numeric: 410,
    },
    {
      plName: 'Niemcy',
      enName: 'Germany',
      alfa2: 'DE',
      alfa3: 'DEU',
      numeric: 276,
    },
    {
      plName: 'Polska',
      enName: 'Poland',
      alfa2: 'PL',
      alfa3: 'POL',
      numeric: 616,
    },
    {
      plName: 'Rosja',
      enName: 'Russian Federation',
      alfa2: 'RU',
      alfa3: 'RUS',
      numeric: 643,
    },
    {
      plName: 'Rumunia',
      enName: 'Romania',
      alfa2: 'RO',
      alfa3: 'ROU',
      numeric: 642,
    },
    {
      plName: 'Słowacja',
      enName: 'Slovakia',
      alfa2: 'SK',
      alfa3: 'SVK',
      numeric: 703,
    },
    {
      plName: 'Stany Zjednoczone',
      enName: 'United States',
      alfa2: 'US',
      alfa3: 'USA',
      numeric: 840,
    },
    {
      plName: 'Szwajcaria',
      enName: 'Switzerland',
      alfa2: 'CH',
      alfa3: 'CHE',
      numeric: 756,
    },
    {
      plName: 'Szwecja',
      enName: 'Sweden',
      alfa2: 'SE',
      alfa3: 'SWE',
      numeric: 752,
    },
    {
      plName: 'Tajwan',
      enName: 'Taiwan, Province of China',
      alfa2: 'TW',
      alfa3: 'TWN',
      numeric: 158,
    },
    {
      plName: 'Turcja',
      enName: 'Turkey',
      alfa2: 'TR',
      alfa3: 'TUR',
      numeric: 792,
    },
    {
      plName: 'Ukraina',
      enName: 'Ukraine',
      alfa2: 'UA',
      alfa3: 'UKR',
      numeric: 804,
    },
    {
      plName: 'Węgry',
      enName: 'Hungary',
      alfa2: 'HU',
      alfa3: 'HUN',
      numeric: 348,
    },
    {
      plName: 'Wielka Brytania',
      enName: 'United Kingdom',
      alfa2: 'GB',
      alfa3: 'GBR',
      numeric: 826,
    },
    {
      plName: 'Wietnam',
      enName: 'Viet Nam',
      alfa2: 'VN',
      alfa3: 'VNM',
      numeric: 704,
    },
    {
      plName: 'Wyspa Man',
      enName: 'Isle of Man',
      alfa2: 'IM',
      alfa3: 'IMN',
      numeric: 833,
    },
    {
      plName: 'Żaden z listy',
      enName: 'Other',
      alfa2: 'XX',
      alfa3: 'NNN',
      numeric: 0,
    },
  ];
}
